### PR TITLE
Update PiAppsTerminalAdvanced.py

### PR DESCRIPTION
**Pull request by pi-dev500**
Permit to all pi-apps users in all os to use this comand-line tool.

### CODE REVIEW

**Comment by pi-dev500** [comment]
@techcoder20 ,it's ready to merge!

**Comment by techcoder20** [comment]
I think doing this might be better where we get the path of the pi-apps folder as we cannot be for sure its in the ~/ directory
```
Pi_Apps_File = open('/usr/local/bin/pi-apps') 
Content = Pi_Apps_File.readlines() 
PiAppsPath = Content[1].replace("#","").replace("/gui", "").strip()
```

**Comment by pi-dev500** [comment]
@techcoder20 ,I have adapted the shell.It's done but pi-apps package must also be updated.

**Comment by pi-dev500** [comment]
@techcoder20 _**The changes are in file install.sh that now detect automaticaly where id the folder where is stored pi-apps's folder**._

**Comment by pi-dev500** [comment]
> I think doing this might be better where we get the path of the pi-apps folder as we cannot be for sure its in the ~/ directory
> ```
> Pi_Apps_File = open('/usr/local/bin/pi-apps') 
> Content = Pi_Apps_File.readlines() 
> PiAppsPath = Content[1].replace("#","").replace("/gui", "").strip()
> ```

Ok,but i think that's not possible because the install script remove **/usr/local/bin/pi-apps** but I can remove this line.

```
sudo rm -f /usr/local/bin/pi-apps
```

An then replace by :
```
if [ ! -f /usr/local/bin/pi-apps];then
  git clone https://github.com/botspot/pi-apps
  ./pi-apps/install
fi

```

**Review by pi-dev500 — COMMENTED** [review]
############################## 
############################## 


It's here there is some changes: install.sh

**Comment by pi-dev500** [comment]
> @techcoder20 ,it's ready to merge!

Yes,now.

**Comment by techcoder20** [comment]
Fixed with commit https://github.com/techcoder20/PiAppsTerminalAdvanced/commit/ca716557855dd3086187b9b750ac24c17b0419f9

**Pull request closed without merging**
